src/Frontend/Models/ErrorViewModel.cs
namespace Frontend.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/Frontend/Models/MyModel.cs
namespace Frontend.Models;

public class MyModel
{
    public bool Bar(int i)
    {
        return false;
    }
}

src/Frontend/Controllers/ArticleController.cs
using Frontend.Data;
using Microsoft.AspNetCore.Mvc;

namespace Frontend.Controllers;

public class ArticleController : Controller
{
    FrontendDbContext _dbContext;

    public ArticleController(FrontendDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public IActionResult Index()
    {
        List<Article> articles = _dbContext.Articles.ToList();

        return View(articles);
    }
}

src/Frontend/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Frontend.Models;

namespace Frontend.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Frontend/Controllers/WeatherController.cs
using Frontend.Data;
using Microsoft.AspNetCore.Mvc;

namespace Frontend.Controllers;

public class WeatherController : Controller
{
    public async Task<IActionResult> Index()
    {
        using (var client = new HttpClient())
        {
            var request = new HttpRequestMessage();
            request.RequestUri = new Uri("http://api/WeatherForecast");
            var response = await client.SendAsync(request);

            var data = await response.Content.ReadAsStringAsync();

            return View("Index", data);
        }        
    }
}

src/Frontend/Views/Article/Index.cshtml
@using Frontend.Data
@model List<Article>

@{
    ViewData["Title"] = "Статьи";
}

<h1>@ViewData["Title"]</h1>

@if (@Model.Count == 0)
{
    <p>Нет статей</p>
}
else
{
    @foreach (var article in @Model)
    {
        <div>@article.Title</div>
    }    
}

src/Frontend/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная страница";
}

<div class="text-center">
    <h1 class="display-4">Добро пожаловать</h1>
</div>

src/Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Frontend.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Статьи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Погода</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Frontend - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Frontend/Views/Weather/Index.cshtml
@{
    ViewData["Title"] = "Погода";
}

<h1>@ViewData["Title"]</h1>

<p>@Model</p>